services:
  api-gateway:
    build: ./blog-api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - post-service
    networks:
      - app-network

  post-service:
    build: ./blog-post-service
    ports:
      - "8081:8081"
    networks:
      - app-network
  
  postgres:
    image: postgres:15
    restart: always
    container_name: blog-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'Root@123'
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
